function [skeleton] = joint_structure (dataFile, fila, columna)
%=============DEBUG INFO====================================
% clear all; close all; fclose all;clc
% dataFile = 'D:\Videos\DataSet\agacharse\Jaison Gonzales\95838 2482012\Esqueleto.csv';
%=========================================================
[~, jointpos] = readSkeleton(dataFile, fila, columna);
dataFields = {'hip_center', 'torso', 'neck', ...
    'head', 'left_shoulder', 'left_elbow', ...
    'left_wrist', 'left_hand', 'right_shoulder', ...
    'right_elbow', 'right_wrist', 'right_hand', ...
    'left_hip', 'left_knee', 'left_ankle', ...
    'left_foot', 'right_hip', 'right_knee', ...
    'right_ankle', 'right_foot'};
skeleton = struct (dataFields{1},[],dataFields{2},[],dataFields{3},[],dataFields{4},[],dataFields{5},[],...
    dataFields{6},[],dataFields{7},[],dataFields{8},[],dataFields{9},[],dataFields{10},[],...
    dataFields{11},[],dataFields{12},[],dataFields{13},[],dataFields{14},[],dataFields{15},[],...
    dataFields{16},[],dataFields{17},[],dataFields{18},[],dataFields{19},[],dataFields{20},[]);
debtime = tic;
for i = 1:fila
    for j = 1:20
        skeleton(i).(dataFields{j}) = jointpos (j,3*(i-1)+1:3*i);
    end
end
toc (debtime)
end